[gcp]
project = "dataverbinders-dev"
bucket = "dataverbinders-dev_test"
# location = "EU"  # currently not used/implemented
# credentials = "" # currently not taken here. User needs to have authentication setup previous to using this library.
                   # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.


[datasets]
datasets = [
    "83583NED",
    "83765NED"
    ]