[gcp]
project = "dataverbinders-dev"
bucket = "dataverbinders-dev_test"
<<<<<<< HEAD
<<<<<<< HEAD
# location = "EU"  # currently not used/implemented
=======
>>>>>>> get gcp project and bucket from config.toml file
=======
# location = "EU"  # currently not used/implemented
>>>>>>> remove development print statements

[datasets]
datasets = [
    "83583NED",
    "83765NED"
    ]