[gcp]
project = "dataverbinders-dev"
bucket = "dataverbinders-dev_test"
# location = "EU"  # currently not used/implemented
<<<<<<< HEAD
=======
>>>>>>> get gcp project and bucket from config.toml file
=======
# location = "EU"  # currently not used/implemented

[datasets]
datasets = [
    "83583NED",
    "83765NED"
    ]