[gcp]
    [gcp.prod]
    project_id = "dataverbinders"
    bucket = "dataverbinders"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.

    [gcp.test]
    project_id = "dataverbinders-test"
    bucket = "dataverbinders-test"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.

    [gcp.dev]
    project_id = "dataverbinders-dev"
    bucket = "dataverbinders-dev"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.
    
[paths]
# Temporary folders are defined here.
# Every source must be defined here, or an error is thrown. #TODO: Make this better
# All folders are nested under the local temp folder, taken by `tempfile.gettempdir()`

cbs = "cbs"
mlz = "mlz"
rivm = "rivm"