version = 1
disable_existing_loggers=false

[formatters]
[formatters.standard]
format="%(asctime)s - %(name)s - %(levelname)s: %(message)s"

[handlers]
[handlers.console]
class="logging.StreamHandler"
level="INFO"
formatter="standard"
stream="ext://sys.stdout"

# [handlers.file]
# class="logging.FileHandler"
# level="WARNING"
# formatter="standard"

[root]
level="INFO"
handlers=["console"]
